Quantum Constraint Solver with dreal
gates list: ['z(1)', 'crz(1.5707963267948966,2,0)', 'cz(0,2)', 'rx(1.5707963267948966,2)', 'h(1)', 't(1)', 'sdg(1)', 'swap(1,0)', 'p(0.7853981633974483,2)', 'z(2)', 'h(1)', 'cp(0.39269908169872414,1,0)', 'p(0.7853981633974483,0)', 'x(1)', 'y(2)', 'cx(2,0)', 'crx(0.39269908169872414,0,2)', 'z(2)', 'z(1)', 't(1)']
target probability: [[2, 0.1083], [5, 0.1458]]
flag: <
Exploring.......................
Traceback (most recent call last):
  File "/home/xiashangzhou/quantum_constraint_solver/QCS.py", line 40, in <module>
    result, time, already_result = quantum_constraint_solver(num_qbits=options.qbit_num,
  File "/home/xiashangzhou/quantum_constraint_solver/quantum_solver.py", line 185, in quantum_constraint_solver
    result, time_full = circuit.prove(overapproximation=False, matrix_method= matrix_method)
  File "/home/xiashangzhou/quantum_constraint_solver/symqv/models/circuit.py", line 95, in prove
    return self._prove_state_model(dump_smt_encoding,
  File "/home/xiashangzhou/quantum_constraint_solver/symqv/models/circuit.py", line 348, in _prove_state_model
    result = subprocess.run(command, capture_output=True, timeout=1000)
  File "/home/xiashangzhou/miniconda/envs/quantum_concolic/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/home/xiashangzhou/miniconda/envs/quantum_concolic/lib/python3.9/subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/home/xiashangzhou/miniconda/envs/quantum_concolic/lib/python3.9/subprocess.py", line 1996, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/home/xiashangzhou/miniconda/envs/quantum_concolic/lib/python3.9/subprocess.py", line 1178, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['/opt/dreal/4.21.06.2/bin/dreal', '--precision', '0.05', '/tmp/tmpin17_h_d.smt2']' timed out after 1000 seconds
